import NavBar from "./components/NavBar";
import "./globals.scss";

export const metadata = {
  title: "Codebeis",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.lineicons.com/4.0/lineicons.css"
        />
      </head>
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
